### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by mxstudios** [skaut/skaut-google-drive-gallery#2005] opened 2023-06-05 13:35 UTC
Hi, great plug-in!

I've seen some forum posts about the unknown error related to the google api setup but can't get mine to work. I have it on one site that I did a year ago and it works perfect. I did the exact same thing and settings on another one and it works for a few hours and then throws the error. It is not the 7 day limit.

It is set to external, and again has the exact settings of another site. What can I provide to help troubleshoot. I know many others are seeing this as well.

Turned on Debug at got error regarding refresh token which makes sense. Looks like it is not being set or passed.

**`refresh token must be passed in or set as part of setAccessToken`**

**Comment by mxstudios** [comment] 2023-06-05 13:47
I added this because similar ticket was closed when OP said revoking worked for him.

**Comment by marekdedic** [comment] 2023-07-02 14:12
Hi,
do you have the Google app set to private or public? And is it set to testing or in production?

**Comment by mjperzl** [comment] 2023-08-02 11:33
Hi, 
I think I have the same Error. 
I have added the Client ID and the Client Secret to the Plugin and the Authorization works perfectly fine.
But I cannot add the Directory which should be displayed.
In my Google OAuth consent Screen, I have set the publishing status to Production (the same error appears in testing) and the User Type to external.

**Comment by marekdedic** [comment] 2023-08-27 09:52
Hi, could you please upgrade to 2.13.4, turn on [debug mode](https://wordpress.org/documentation/article/debugging-in-wordpress/) and send me the output? Thanks

**Comment by marekdedic** [comment] 2023-08-27 09:53
Closing as duplicate of #1987

**Closed by marekdedic** 2023-08-27 09:53 UTC
