### ISSUE TITLE
500 Internal Server Error on page

### ISSUE THREAD

**Issue by terryzzZ** [skaut/skaut-google-drive-gallery#127] opened 2019-04-09 05:39 UTC
Hi there,

I just installed the plugin successfully and granted permission successfully as well. The folder list is already there that I can choose the root path.

However, after I put shortcode on the page, it displayed nothing on the page with a 500 Internal Server Error. I am wondering if it's because I put my site on localhost. (but I can see the folder list that I should already fix the permission issue, right? )

Please let me know if you have any ideas on it.

![Screen Shot 2019-04-09 at 3 38 55 pm](https://user-images.githubusercontent.com/18039986/55775754-aab87b80-5add-11e9-9f0f-6a8196c831da.png)

**Comment by terryzzZ** [comment] 2019-04-09 07:15
I tried it on an active site but still get a 500 error respond

**Comment by marekdedic** [comment] 2019-04-09 07:46
Hi,
if you can choose the root path then indeed you have the permissions granted.

I'll need some more info to determine what is the issue.
1. What version of PHP do you have
2. What version of WordPress do you have
3. Is there anything in the server error log? That would probably help me the most
4. The gallery makes an ajax request - I presume that's the one giving you the 500. Is there anything in the response?

Thanks

**Comment by terryzzZ** [comment] 2019-04-15 13:31
Hi,

Please find the related information below:

1. PHP 7.3.0

2. WP 5.1.1

3. It' what I had at the moment (please let me know if you have any idea about how to get more logs)
<img width="1349" alt="Screen Shot 2019-04-15 at 23 27 21" src="https://user-images.githubusercontent.com/18039986/56136473-364a7480-5fd6-11e9-8020-8eb5214630ee.png">

4. I am not sure if they're what you look for.
<img width="1170" alt="Screen Shot 2019-04-15 at 23 30 41" src="https://user-images.githubusercontent.com/18039986/56136665-980ade80-5fd6-11e9-87d2-c25cd6d6b175.png">
<img width="1167" alt="Screen Shot 2019-04-15 at 23 30 54" src="https://user-images.githubusercontent.com/18039986/56136668-993c0b80-5fd6-11e9-93c7-fd6560075505.png">

Thank you so much!

**Comment by terryzzZ** [comment] 2019-04-15 13:44
Hi,

I think I fixed it. It seems like my images folder on G-Drive not working properly. It works once I changed the root of folder. 

Sorry my bad. Thank you so much for your time!

**Comment by marekdedic** [comment] 2019-04-16 07:57
Ok. Since the issue is fixed and I don't have a way to replicate it, I'm closing it.

Thanks!

**Closed by marekdedic** 2019-04-16 07:57 UTC
