### ISSUE TITLE
Folder image thumbnail

### ISSUE THREAD

**Issue by mtomasg** [skaut/skaut-google-drive-gallery#94] opened 2018-11-05 21:37 UTC
Is there any way to set the foto of the thumbnail of a folder. Or any workaround (like the first in alphabetical order)?

Thanks in advance, your plugin is very fine!

**Comment by GenaBitu** [comment] 2018-11-05 22:07
Hi, there is currently no way to choose which photo gets used as the thumbnail (it's always the first photo in whatever ordering is used for images), but it's definitely something worth exploring - in fact, we have an issue open for this: #54 

I'm gonna close this issue as it's a duplicate of #54 (correct me if I'm wrong), but thanks, this helps us set preferences.

**Closed by GenaBitu** 2018-11-05 22:07 UTC
