### ISSUE TITLE
Forward and backward buttons squeezed on mobile

### ISSUE THREAD

**Issue by StachRedeker** [skaut/skaut-google-drive-gallery#1304] opened 2022-03-12 10:42 UTC
When viewing a single image on a mobile device, the forward and backward buttons look squeezed:
![buttons_on_mobile](https://user-images.githubusercontent.com/64889011/158014890-2dfbc3c6-8cc0-43ce-ba73-b2e666ae657f.png)

**Comment by marekdedic** [comment] 2022-03-14 13:19
Hi,
thanks for the bug report, this definitely shouldn't happen.

We'll look into it, however, I can't promise any timeframe as this is a relatively minor thing :)

**Comment by marekdedic** [comment] 2022-03-14 13:22
Related: #90, #267

**Comment by StachRedeker** [comment] 2022-03-14 14:50
> I can't promise any timeframe as this is a relatively minor thing :)

Understandable, don't worry about it.

**Comment by marekdedic** [comment] 2022-08-09 11:29
Should be covered by marekdedic/imagelightbox#382

**Comment by marekdedic** [comment] 2024-05-03 11:31
Should be fixed by new releases of imagelightbox, let me know if the issue is still present ;)

**Closed by marekdedic** 2024-05-03 11:31 UTC
Labels: Bug, Design & UI, Open to PRs
