### ISSUE TITLE
Mobile Version Image Spacing (Responsive Position)

### ISSUE THREAD

**Issue by mauricekindermann** [skaut/skaut-google-drive-gallery#79] opened 2018-09-14 00:22 UTC
The CSS positioning (top: [x]) breaks on mobiles, screenshot: 

![2018-09-14_1019](https://user-images.githubusercontent.com/3828998/45522679-dc978700-b807-11e8-942e-5a64dc8469aa.png)

They're all inline styles and because they're positioned absolutely there's no way to fix it with a CSS hack. Needs to be fixed in the core CSS files/library.

**Comment by GenaBitu** [comment] 2018-09-14 11:59
Hi, could you please give us a link to a broken gallery? If you don't feel comfortable posting it online, could you please send it to genabitu@gmail.com?

Thank you

**Comment by GenaBitu** [comment] 2018-09-27 08:30
I think this should be fixed along with #80. If the issue is still present after the next update, we will look into it more...

**Closed by GenaBitu** 2018-09-27 08:30 UTC
Labels: Bug, Waiting for 3rd party
